/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 computer_1.glb --transform 
Files: computer_1.glb [13.76MB] > C:\Users\Happy yadav\Desktop\Happy rao\public\models\computer_1-transformed.glb [1.06MB] (92%)
Author: sudreyskr (https://sketchfab.com/sudreyskr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-1-541747a461f84142a113e2f591a7eb9b
Title: Computer #1
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computer_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sub_Control_Computer_Sub_Control_Material_0.geometry} material={materials.Sub_Control_Material} position={[0, 0.208, 0]} scale={1.5} />
      <mesh geometry={nodes.Glass_Glass_Material_0.geometry} material={materials.Glass_Material} position={[0, 0.208, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/computer_1-transformed.glb')
