/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 logo.glb --transform 
Files: logo.glb [194.16KB] > C:\Users\Happy yadav\Desktop\Happy rao\public\models\logo-transformed.glb [19.69KB] (90%)
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export default function LogoPic(props) {
  const { nodes, materials } = useGLTF('/models/logo-transformed.glb')
  const modelRef = useRef();
  useFrame(() =>{
modelRef.current.rotation.y += 0.001;
  })
  return (
    <group {...props} dispose={null}
     ref={modelRef} scale={[5,5,5]} rotation={[9,9,9]} position={[0,0,0]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/models/logo-transformed.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hat-transformed.glb --transform 
Files: hat-transformed.glb [227.05KB] > C:\Users\Happy yadav\Desktop\Happy rao\public\models\hat-transformed-transformed.glb [226KB] (0%)

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function HatModel(props) {
  const { nodes, materials } = useGLTF('/models/hat-transformed-transformed.glb')
  const modelRef = useRef();
  useFrame(() =>{
modelRef.current.rotation.y += 0.005;
  })
  return (
    <group {...props} dispose={null}
    ref={modelRef} scale={[1.8,1.8,1.8]} rotation={[0.4,-1,0]} position={[0,0,0]} >
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} position={[0, -3.867, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/hat-transformed-transformed.glb')
 */